# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

In [43]:
# Importing Libraries

import os
import numpy as np
import pandas as pd

In [44]:
# importing data set
marketing = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv')

In [45]:
marketing.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [46]:
marketing.drop(columns=['Unnamed: 0'], inplace=True)

In [47]:
marketing.columns

Index(['Customer', 'State', 'Customer Lifetime Value', 'Response', 'Coverage',
       'Education', 'Effective To Date', 'EmploymentStatus', 'Gender',
       'Income', 'Location Code', 'Marital Status', 'Monthly Premium Auto',
       'Months Since Last Claim', 'Months Since Policy Inception',
       'Number of Open Complaints', 'Number of Policies', 'Policy Type',
       'Policy', 'Renew Offer Type', 'Sales Channel', 'Total Claim Amount',
       'Vehicle Class', 'Vehicle Size', 'Vehicle Type'],
      dtype='object')

Decided not to change the column names as they are already standardize, even though not best practices. Could be that the company prefers like this and would just be a moo point to do it

In [48]:
marketing['Response'].value_counts()

Response
No     8813
Yes    1466
Name: count, dtype: int64

In [49]:
marketing['Response'].isnull().sum()

np.int64(631)

In [50]:
marketing['Total Claim Amount'].isnull().sum()

np.int64(0)

In [51]:
marketing['Total Claim Amount'].dtype

dtype('float64')

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [52]:
low_tca = (marketing['Total Claim Amount'] < 1000) & (marketing['Response'] == 'Yes')
low_tca_df = marketing[low_tca]
low_tca_df

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,66839,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,79487,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,41479,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,63774,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,...,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,25998,...,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,...,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,52583,...,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,37722,...,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [53]:
marketing.columns

Index(['Customer', 'State', 'Customer Lifetime Value', 'Response', 'Coverage',
       'Education', 'Effective To Date', 'EmploymentStatus', 'Gender',
       'Income', 'Location Code', 'Marital Status', 'Monthly Premium Auto',
       'Months Since Last Claim', 'Months Since Policy Inception',
       'Number of Open Complaints', 'Number of Policies', 'Policy Type',
       'Policy', 'Renew Offer Type', 'Sales Channel', 'Total Claim Amount',
       'Vehicle Class', 'Vehicle Size', 'Vehicle Type'],
      dtype='object')

In [54]:
# pivot table with Monthly Premium Auto by Policy Type and Gender
responded_yes = marketing[marketing['Response'] == 'Yes']

premium = responded_yes.pivot_table(index='Policy Type', columns='Gender', values=['Monthly Premium Auto', 'Customer Lifetime Value'], aggfunc='mean').round(2)

premium

               Customer Lifetime Value          Monthly Premium Auto
Gender                               F        M                    F      M
Policy Type
Corporate Auto                 7712.63  7944.47                94.30  92.19
Personal Auto                  8339.79  7448.38                99.00  91.09
Special Auto                   7691.58  8247.09                92.31  86.34

In [55]:
# compare these insights to total_claim_amount patterns, and discuss which segments appear most profitable or low-risk for the company.
# pivot table of total_claim_amount, gender and policy type

tca = responded_yes.pivot_table(index='Policy Type', columns='Gender', values='Total Claim Amount', aggfunc='mean').round(2)

tca

Gender               F       M
Policy Type
Corporate Auto  433.74  408.58
Personal Auto   452.97  457.01
Special Auto    453.28  429.53

The premiums and the total claims are very similar, but the personal auto average for woman have a 8 moneys difference from the one for man (and it is the highest premium).  The presonal auto also has the highest CLV, so marketing could focus on personal auto policies focused on women

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [56]:
customers_per_state = marketing.groupby('State')['Customer'].count()
customers_per_state[customers_per_state > 500]

State
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: Customer, dtype: int64

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [57]:
clv_edu_gender = marketing.pivot_table(index='Education', columns='Gender', values='Customer Lifetime Value', aggfunc=['max', 'min', 'median', 'sum']).round(2)

clv_edu_gender

                           max                min            median           \
Gender                       F         M        F        M        F        M
Education
Bachelor              73225.96  67907.27  1904.00  1898.01  5640.51  5548.03
College               61850.19  61134.68  1898.68  1918.12  5623.61  6005.85
Doctor                44856.11  32677.34  2395.57  2267.60  5332.46  5577.67
High School or Below  55277.45  83325.38  2144.92  1940.98  6039.55  6286.73
Master                51016.07  50568.26  2417.78  2272.31  5729.86  5579.10

                              sum
Gender                          F            M
Education
Bachelor              13386258.11  12110061.83
College               12460107.91  12851725.02
Doctor                 1465701.78   1490482.06
High School or Below  13793600.12  12680914.19
Master                 3874600.25   3365559.06

In [58]:
# Redid the pivot table without gender as differences between genders are minimum.
clv_edu = marketing.pivot_table(index='Education', values='Customer Lifetime Value', aggfunc=['max', 'min', 'median', 'sum']).round(2)

clv_edu

,max,min,median,sum
,Customer Lifetime Value,Customer Lifetime Value,Customer Lifetime Value,Customer Lifetime Value
Education,,,,
Bachelor,73225.96,1898.01,5579.38,25496319.95
College,61850.19,1898.68,5813.63,25311832.93
Doctor,44856.11,2267.60,5423.14,2956183.84
High School or Below,83325.38,1940.98,6189.35,26474514.31
Master,51016.07,2272.31,5680.47,7240159.30

The doctors are the one with the least overall sum, but the range of their policies are the smaller than other eductations levels, while highschool has the highest - might be interesting for sales people to know that they should invest more time in convincing that demographics as their policies seem to be worth more than high school demographics (a matter of time spent vs return)

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [59]:
# your code goes here